theme: jekyll-theme-minimal
title: mADAme
description: In the vast world of cinema, where stories shape perceptions, a critical question emerges. How does the gender of a director influence the portrayal of women on screen?
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
